import { Navbar } from '@/components/Navbar';
import { Providers } from '@/components/Providers';
import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const inter = Recursive({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Providers>{children}</Providers>
        <Toaster
          position="top-right"
          icons={{
            success: '🎉',
            error: '❌',
            warning: '⚠️',
            info: 'ℹ️',
          }}
          toastOptions={{
            duration: 4000,
            classNames: {
              success: 'bg-green-500 border-green-500',
              error: 'bg-rose-500 border-rose-500',
              warning: 'bg-yellow-500 border-yellow-500',
              info: 'bg-blue-500 border-blue-500',
            },
          }}
        />
      </body>
    </html>
  );
}
